/* Generated By:JavaCC: Do not edit this line. Simple3Constants.java */
public interface Simple3Constants {

  int EOF = 0;
  int REPL = 5;
  int WHILE = 6;
  int THIS = 7;
  int BEGIN = 8;
  int SUPER = 9;
  int NEW = 10;
  int ABSTRACT = 11;
  int OVERRIDE = 12;
  int IF = 13;
  int PARAM = 14;
  int REQ = 15;
  int END = 16;
  int OF = 17;
  int LET = 18;
  int MIXIN = 19;
  int THEN = 20;
  int INSTR = 21;
  int LBRACE = 22;
  int RBRACE = 23;
  int ID = 24;
  int INTEGER_LITERAL = 25;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"repl\"",
    "\"while\"",
    "\"this\"",
    "\"begin\"",
    "\"super\"",
    "\"new\"",
    "\"abstract\"",
    "\"override\"",
    "<IF>",
    "\"param\"",
    "\"req\"",
    "\"end\"",
    "\"of\"",
    "\"let\"",
    "\"mixin\"",
    "\"then\"",
    "\"instr\"",
    "\"{\"",
    "\"}\"",
    "<ID>",
    "<INTEGER_LITERAL>",
    "\"end;\"",
    "\".\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"<-\"",
    "\"=\"",
  };

}
