/* Generated By:JavaCC: Do not edit this line. Simple1Constants.java */
public interface Simple1Constants {

  int EOF = 0;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
  };

}
