/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package Magda.Parser;

public interface ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int INCLUDE = 10;
  int LET = 11;
  int NULL = 12;
  int TRUE = 13;
  int FALSE = 14;
  int SUPER = 15;
  int VOID = 16;
  int THIS = 17;
  int BEGIN = 18;
  int END = 19;
  int NEW = 20;
  int ABSTRACT = 21;
  int OVERRIDE = 22;
  int REQUIRED = 23;
  int OPTIONAL = 24;
  int INITIALIZES = 25;
  int IF = 26;
  int ELSE = 27;
  int WHILE = 28;
  int MIXIN = 29;
  int OF = 30;
  int WHERE = 31;
  int RETURN = 32;
  int NATIVEINSTRUCTION = 33;
  int ID = 34;
  int STRING_LITERAL = 35;
  int BYTE_LITERAL = 36;
  int INTEGER_LITERAL = 37;
  int FLOAT_LITERAL = 38;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 9>",
    "\"include\"",
    "\"let\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"super\"",
    "\"void\"",
    "\"this\"",
    "\"begin\"",
    "\"end\"",
    "\"new\"",
    "\"abstract\"",
    "\"override\"",
    "\"required\"",
    "\"optional\"",
    "\"initializes\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"mixin\"",
    "\"of\"",
    "\"where\"",
    "\"return\"",
    "<NATIVEINSTRUCTION>",
    "<ID>",
    "<STRING_LITERAL>",
    "<BYTE_LITERAL>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "\".\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"==\"",
    "\"=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
  };

}
