/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */
public interface ExampleConstants {

  int EOF = 0;
  int ID = 6;
  int INT = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\",\"",
    "<ID>",
    "<INT>",
  };

}
